### ISSUE TITLE
Digital Twin: Website Update 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#72]
- [ ] DT Navigate bar add Threefold Universe / Part of the Ecosystem: https://github.com/threefoldfoundation/www_threefold_twin/issues/69 (@Sacha96 @AlexandreHannelas)
- [ ] Add two Experiences: Alternative to Facebook, Alternative to Linkedin https://github.com/threefoldfoundation/www_threefold_twin/issues/70 (@Sacha96 @AlexandreHannelas)
- [ ] Digital Twin for Life: Enabling People to register to sign up and reserve their Digital Twin https://github.com/threefoldfoundation/www_threefold_twin/issues/71 (@nbabenko) 
- [x] Change "Video Chat" to "Meet" https://github.com/threefoldfoundation/www_threefold_twin/issues/65 (@AlexandreHannelas @Vilnite @Zizaster) 
- [x] Add P2P page on website: https://github.com/threefoldfoundation/home/issues/127 (@AlexandreHannelas @Vilnite  @Zizaster ) 
- [ ] Integrate Liquid Quick Exchange on Website https://github.com/threefoldfoundation/www_threefold_twin/issues/62 (@nbabenko) 
- [ ] Work on the Onboarding funnel https://github.com/threefoldfoundation/www_threefold_twin/issues/22 (@AlexandreHannelas @Sacha96)

**Comment by AlexandreHannelas** [comment]
Closed because of Duplicationhttps://github.com/threefoldfoundation/www_threefold_twin/issues/73
