### ISSUE TITLE
Digital Twin (for Life) updated, 15th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_twin#73]
**DESCRIPTION:**
"With major tech giants being hacked lately it is the time to bring up a new social and business networking platforms where user data is secure. Lets create those two concepts and bring it up on Digital Twin website asap, together with DT for Life page and How It Works on wiki."

**DEADLINE:** 18th April

**TO DO:**
- [x] DT Navigate bar add Threefold Universe / Part of the Ecosystem: https://github.com/threefoldfoundation/www_threefold_twin/issues/69 (@Vilnite @Sacha96 @AlexandreHannelas)
- [x] Add two Experiences: Alternative to Facebook, Alternative to Linkedin https://github.com/threefoldfoundation/www_threefold_twin/issues/70 (@Sacha96 @AlexandreHannelas)
- [x] Digital Twin for Life: Edit CTA https://github.com/threefoldfoundation/www_threefold_twin/issues/71 (@Vilnite @AlexandreHannelas)
- [x] Change "Video Chat" to "Meet" https://github.com/threefoldfoundation/www_threefold_twin/issues/65 (@AlexandreHannelas @Vilnite @Zizaster) 
- [x] Add P2P page on website: https://github.com/threefoldfoundation/home/issues/127 (@AlexandreHannelas @Vilnite  @Zizaster ) 
- [x] Integrate Liquid Quick Exchange on Website https://github.com/threefoldfoundation/www_threefold_twin/issues/62 (@nbabenko) 
- [x] Work on the Reservation onboarding funnel https://github.com/threefoldfoundation/www_threefold_twin/issues/22 (@AlexandreHannelas @Sacha96) 
- [x] Add DT for Life page, https://github.com/threefoldfoundation/www_threefold_twin/issues/74 (@AlexandreHannelas, @Sacha96, @Vilnite, @Zizaster)
- [x] Create page and content on how Microsoft, Amazon and all these big tech companies are being hacked and how our solution stands out: https://github.com/threefoldfoundation/info_digitaltwin/issues/14 (@AlexandreHannelas)
- [x] Review Wiki: https://github.com/threefoldfoundation/www_threefold_twin/issues/51 (@despiegk @Sacha96 @AlexandreHannelas)
- [x] DigitalTwin Wiki - Create own DT live chat: https://github.com/threefoldfoundation/info_digitaltwin/issues/12 (@sabrinasadik @ehab-hassan)
- [x] Digital Twin T&C: https://github.com/threefoldfoundation/home_private/issues/13 (@nbabenko @down2basics)
- [x] Remove TF logo from DT experience portal, https://github.com/threefoldfoundation/home/issues/153 (@ken-de-moor)
- [x] Add DT For Life page: https://github.com/threefoldfoundation/www_threefold_twin/issues/75 (@Vilnite @AlexandreHannelas)
- [x] Digital Twin website edit: https://github.com/threefoldfoundation/www_threefold_twin/issues/78 (@Vilnite)

**Comment by AlexandreHannelas** [comment]
Story #70, will be pushed to next week and will go live at same time than DT reservation #77
