### ISSUE TITLE
Digital Twin: Website Edits 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#78]
![Screen Shot 2021-04-16 at 10 14 18 AM](https://user-images.githubusercontent.com/78421574/115035727-27e90900-9ecd-11eb-9ee4-dd817d79bf28.png)
- [x] Increase text size (moved to https://github.com/threefoldfoundation/www_threefold_twin/issues/81)

![Screen Shot 2021-04-16 at 3 18 47 PM](https://user-images.githubusercontent.com/78421574/115035817-3e8f6000-9ecd-11eb-9d3e-32b924950a24.png)
- [x] Increase text size or illustration size (moved to https://github.com/threefoldfoundation/www_threefold_twin/issues/81)

![Screen Shot 2021-04-16 at 3 18 55 PM](https://user-images.githubusercontent.com/78421574/115035996-6252a600-9ecd-11eb-8aed-595cb5f57aa0.png)
- [x] Increase text size or block size (moved to https://github.com/threefoldfoundation/www_threefold_twin/issues/81)

- [x] home page/Digitaltwin applications block/Meet: frst to First
- [x] home page/Digitaltwin applications block/File Storage: fles to files
- [x] Experiences/Chat/Exchange Freely: Make text size consistent with other 
- [x] Experiences/Chat/Stay in touch with your circles: fy to fly 
- [x] Experiences/Chat/ Available now..: (1) Remove double space between # and with (2) make text size consistent with other 
- [x] Experiences/File Storage/Seamless Compatibility: fle to file --> x 2
- [x] Experiences/File Storage/ Your data is safe: fles to file
- [x] Experiences/File Storage/Ultra Secure: fles to files 
- [x] Experiences/File Storage/Sharing Made Simple: fles to files 
- [x] Experiences/Office/All you Need: offce to Office 
- [x] Experiences/Office/Private Environment: fle/s to files --> x2
- [x] Experiences/Office/Easy Access: fles to files 
- [x] Experiences/Web Publisher/A Secure Experience: defne to define 
- [x] Experiences/Web Publisher/Compatible: Make text size consistent with others
- [x] Experiences/Payments/Multi-currency Wallet: beneft to benefit, fnd to find 
- [x] Experiences/Payments/Ultra Secure: Beneft to Benefit
- [x] Experiences/Payments/Coming Soon to Digital Twin: frst to first. Make text size consistent with other

**Comment by AlexandreHannelas** [comment]
Talk to @Vilnite, we move the issue for next sprint web 2.8.2 to be finished

**Comment by AlexandreHannelas** [comment]
- [x] Fix About us/Contact us link on website 

![Screen Shot 2021-04-18 at 4 27 50 PM](https://user-images.githubusercontent.com/78421574/115149162-1afe1e00-a063-11eb-8d37-42d79f1f179e.png)
