### ISSUE TITLE
Digital Twin (for Life)

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#80]
The focus is to make Reservation of Digital Twin for Life possible

Deadline: 25th of April:

- [x] Add two Experiences: Alternative to Facebook, Alternative to Linkedin: #70 (@Sacha96 @AlexandreHannelas @Zizaster )
- [x] Add Reservation page #77  (@AlexandreHannelas @Zizaster) 
- [x] Fix all bugs and errors on Digital Twin website - Mobile Phone view (https://github.com/threefoldfoundation/home/issues/146) (@Vilnite @ehab-hassan ) 
- [ ]  Implement Digital Twin reservation on TF Connect (https://github.com/threefoldtech/threefold_connect/issues/232) (@ken-de-moor)
- [x] Digital Twin add wiki pages: (https://github.com/threefoldfoundation/info_digitaltwin/issues/16) (@AlexandreHannelas) 
- [x] Website edits https://github.com/threefoldfoundation/www_threefold_twin/issues/81 (@samaradel )
- [x] Add navigation bar to each experience page (https://github.com/threefoldfoundation/www_threefold_twin/issues/56) (@ehab-hassan @samaradel)
