### ISSUE TITLE
DT for Life_2.7.4, 23rd April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_twin#82]
**DESCRIPTION:**
"Improving DT website with Digital Twin for Life focus."

**DEADLINE:** 23rd April

**TO DO:**
- [x] Add two more Experiences, https://github.com/threefoldfoundation/www_threefold_twin/issues/70 (@Sacha96 , @AlexandreHannelas, @Vilnite )
- [x] Add navigation buttons for experiences, https://github.com/threefoldfoundation/www_threefold_twin/issues/56 (@samaradel )
- [x] Rework hardcoded image components, https://github.com/threefoldfoundation/www_threefold_twin/issues/81 (@samaradel )
- [x] Add Reservation page #77  (@AlexandreHannelas @Zizaster, @ehab-hassan ) 
- [x] Fix all bugs and errors on Digital Twin website - Mobile Phone view (https://github.com/threefoldfoundation/home/issues/146) (@ehab-hassan ) 
- [x] Digital Twin add wiki pages: (https://github.com/threefoldfoundation/info_digitaltwin/issues/16) (@AlexandreHannelas)
- [x] Add Partners quote on home page #83 (@Vilnite, @ehab-hassan )
- [x] Add Roadmap on DT reservation page #84 (@AlexandreHannelas @Vilnite, @ehab-hassan )
